### ISSUE TITLE
Congratulations!

### ISSUE THREAD

**Issue by PySimpleGUI** [Zain-Bin-Arshad/pdf-viewer#4]
Hi!

It's been a bit since I last looked at your screenshots.  I'm being 100% honest and I saw with no hesitation in saying that they're better than any PDF reader I've ever seen written in PySimpleGUI.  There were a number of challenges and you stuck with it.  That's an impressive feat on its own.

My hope is that as PySimpleGUI continues to mature that these areas that were difficult become easier to work with.  Thank you for posting screenshots in your readme and for posting an entry on the PySimpleGUI Wiki.  I'm sure everyone that sees them appreciates you taking them.  So often it's not possible to understand / see what a Python program does because it lacks a GUI.  By having one and sharing it, your users get to see the end result.

I don't know if you've approached any of the GitHub repos like Vinta that lists applications.  I think it's worth you going through the process.  It can take months to get the approval and be integrated into the list, but once you're there, you're there for life basically.  It depends on the goals of your project and if you want to attract more users.  If your goal was to create it and actively attracting users is not something you're interested in, then by all means don't waste your time.... enjoy that time doing something else!

Congrats again.  I hope you feel proud about what you've created as I see plenty of reasons you could be.

**Comment by Zain-Bin-Arshad** [comment]
Hello @PySimpleGUI , thanks for being honest. Hearing this from you means a lot. I always go through issues and accouchements of PySimpleGUI and appreciate your work on Buttons, etc.

A lot can be improved because you have improved PySimpleGUI a lot since I created this application. Consequently, there are a number of things that don't need a workaround, etc. Moreover, the code base can be improved. But yeah, this is still working and provides a great building block for anyone who wants complete access to the source code of PDF-viewer.

> I don't know if you've approached any of the GitHub repos like Vinta that lists applications. I think it's worth you going through the process.

I'm sorry, but I didn't get what you were saying. I surely want people to use it, improve the code, and improve this application. Can you please shed some light on what you are trying to say here? I would appreciate this.

Yes, I feel proud because I completed 60% of this project in a week or so. The `Night Mode`  feature I did in about 80 minutes. I still remember working day and night to get it done; the simplicity and power of PySimpleGUI made it possible.

**Comment by Zain-Bin-Arshad** [comment]
@PySimpleGUI Should I close this thread ?

**Comment by PySimpleGUI** [comment]
Sure!  No need to hold it open.  I'm subscribed to it so if you comment, I'll get an email.  No need to have any more open issues than required and this one certainly doesn't need to sit open.
