### ISSUE TITLE
Error when trying to open PDF file

### ISSUE THREAD

**Issue by boesiii** [Zain-Bin-Arshad/pdf-viewer#6]
I get an error when I try and open a PDF file.  The error message is "Sorry this file can't be opened."

Attached is a sample file I used.

[sample3.pdf](https://github.com/Zain-Bin-Arshad/pdf-viewer/files/9710710/sample3.pdf)

**Comment by Zain-Bin-Arshad** [comment]
I am able to view this file just fine. Seems like there is some issue in the `fitz` package that you have installed, can you please make sure that version is same as that given in `requirements.txt`? See what happens when you remove [this try/except block](https://github.com/Zain-Bin-Arshad/pdf-viewer/blob/master/pdfviewer.py#L152)

![Screenshot](https://user-images.githubusercontent.com/49767636/195443685-a193a1bf-4653-4d27-ab94-6a545c42495d.jpg)

**Comment by NicolasMICAUX** [comment]
Same error.
Btw,  why the "requirements.txt" list package `fitz` which is a neuroimaging package from 2017 (https://pypi.org/project/fitz/) ?
I know that PyMuPDF has package domain `fitz`.

When I remove the installation of this weird fitz package from requirements, I still get an error, but not at the same place : 
`'Page' object has no attribute 'getDisplayList'`

**Comment by NicolasMICAUX** [comment]
About the name "fitz": https://documentation.help/PyMuPDF/intro.html#note-on-the-name-fitz

**Comment by NicolasMICAUX** [comment]
The last error is because of the last updates of PyMuPDF : https://pymupdf.readthedocs.io/en/latest/znames.html
Which version of PyMuPDF are u using?

**Comment by Zain-Bin-Arshad** [comment]
Fixed merged, so closing this one.
